# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0004_revision_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='object updated'),
        ),
    ]
