# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0005_auto_20160407_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.IntegerField(choices=[(2, 'Approved'), (1, 'Pending'), (0, 'Reject')], default=1),
        ),
    ]
