# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0006_version_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='status',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.IntegerField(choices=[(2, 'Approved'), (1, 'Pending'), (0, 'Created'), (-1, 'Rejected')], default=1),
        ),
    ]
