# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0008_auto_20160415_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='status',
            new_name='version_status',
        ),
    ]
